export const tables = {
    accounts: "accounts",
    account_products: "account_products",
    auditLogs: "audit_logs",
    branches: "branches",
    employees: "employees",
    employee_roles: "employee_roles",
    roles: "roles",
    feedbacks: "feedbacks",
    loans: "loans",
    queries: "queries",
    serviceTickets: "service_tickets",
    transactions: "transactions",
    userAddresses: "user_addresses",
    userCreditAccounts: "user_credit_accounts",
    userCreditBureauData: "user_credit_bureau_data",
    userCreditEnquiries: "user_credit_enquiries",
    userKYCDocuments: "user_kyc_documents",
    userOtps: "user_otps",
    users: "users",
    videoKYCSessions: "video_kyc_sessions",
    videoQueries: "video_queries",
};
